### ISSUE TITLE
How to set language server IP + Port?

### ISSUE THREAD

**Issue by huanghantao** [qualified/lsp-ws-proxy#22]
Can I use it like this:

```bash
target/debug/lsp-ws-proxy --listen 3001 -- langserver 127.0.0.1:9901
```

**Comment by kazk** [comment]
No, the proxy uses stdio to communicate with the language server. Does your server support option like `--stdio`? If not, it might be possible to write some wrapper with `netcat`.

```bash
#!/bin/bash
PORT=9901
nc -l -p $PORT <&0 >&1 &
langserver 127.0.0.1:$PORT > /dev/null
```

**Comment by kazk** [comment]
For https://github.com/phpactor/phpactor/issues/1301, I believe it uses stdio by default unless you specify the address.

Try
```bash
lsp-ws-proxy --listen 3001 -- phpactor language-server
```

**Comment by huanghantao** [comment]
Thank you!
