### ISSUE TITLE
Is there any way to restrict listing parent directory?

### ISSUE THREAD

**Issue by johnny-mh** [qualified/lsp-ws-proxy#36]
Thank you for creating a great library. I have a question that arose while using the library. When querying a file, I understand that it is done based on the rootUri. Is it possible to prevent referencing the parent path in this case?

![image](https://github.com/qualified/lsp-ws-proxy/assets/1061205/206aba18-419c-4546-a7d5-111be9719b2a)

If I set the rootUri to 'file://workspace', I would like the listing to be limited to the folders within the workspace folder.

**Comment by kazk** [comment]
I'm glad you found this project useful :)

No, there's no way to restrict that, and it's definitely out of scope for this project. `lsp-ws-proxy` is a minimal proxy to allow communicating with remote Language Servers via WebSocket, and doesn't control what each Language Server does.

Maybe you can remove the read permission (`chmod o-r`) on the parent directories to prevent listing contents.
